### ISSUE TITLE
Add API for Swell to get address profile status

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal-server#10]
We need a new private API that will return the status of the address sent of the request. Example:

```
GET /api/auth/profile-status/[WALLET_ADDRESS]
```

Response:
```json
{ "exists": true, "profile": false  }
```

Meaning that wallet address was used for Portal sign-in, but haven't completed their profile.

API should be private - access token will be used to perform requests.

**Comment by yatsunastya** [comment]
Checked ✅
Version: [3.1.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.0)

Account is connected, but it's not signed-in and doesn't have e-mail.
```
{"exists":false,"profile":false}
```
Account is connected and signed-in, but doesn't have e-mail.
```
{"exists":true,"profile":false}
```
Account is connected, signed-in and has e-mail. 
```
{"exists":true,"profile":true}
```
