### ISSUE TITLE
Add separate auth cookies for different instances of portal-server

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/portal-server#5]
Currently, after sign-in cookie with name "auth_token" sent to the browser, meaning that login on testnet portal will override login from mainnet portal.

We need to add prefixes for "auth_token" cookie based on env (mainnet/testnet/etc)

**Comment by yatsunastya** [comment]
Checked ✅
Version: [3.1.0-beta.0](https://github.com/skalenetwork/portal/releases/tag/3.1.0-beta.0)

Same account stays signed-in on all Portal versions - Mainnet, Legacy, Alpha
